name: test01
on:
  push:
env:
  BASE_URL: ${{ secrets.BASE_URL }}
  DASHBOARD_EMAIL: ${{ secrets.DASHBOARD_EMAIL }}
  DASHBOARD_PASSWORD: ${{ secrets.DASHBOARD_PASSWORD }}
  DASHBOARD_ERROR_EMAIL: ${{ secrets.DASHBOARD_ERROR_EMAIL }}
  DASHBOARD_ERROR_PASSWORD: ${{ secrets.DASHBOARD_ERROR_PASSWORD }}

jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install software
        run: sudo apt-get install -y chromium-browser
      - name: Install the necessary packages
        run: pip install requests webdriver-manager selenium pytest pydantic-settings
      - name: Run the PyTest script
        run: pytest -rA
