name: selenium-tests
on:
  push:

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  DASHBOARD_EMAIL: ${{ secrets.DASHBOARD_EMAIL }}
  DASHBOARD_PASSWORD: ${{ secrets.DASHBOARD_PASSWORD }}
  DASHBOARD_ERROR_EMAIL: ${{ secrets.DASHBOARD_ERROR_EMAIL }}
  DASHBOARD_ERROR_PASSWORD: ${{ secrets.DASHBOARD_ERROR_PASSWORD }}
  ALLURE_RESULTS_PATH: allure-results # Define ALLURE_RESULTS_PATH here
  

jobs:
  tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./tests
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget apt-transport-https

      - name: Add Google Chrome repository
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

      - name: Install Google Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      - name: Install the necessary packages
        run: pip install requests webdriver-manager selenium pytest pydantic-settings allure-pytest

      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls -la

      - name: Prepare Allure history
        run: mkdir -p ../${{ env.ALLURE_RESULTS_PATH }}

      - name: Run the PyTest script
        run: |
          cd ..
          pytest -rA --alluredir=../${{ env.ALLURE_RESULTS_PATH }}

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ${{ env.ALLURE_RESULTS_PATH }}
          allure_history: allure-history
          keep_reports: 5
